# Generated by Django 3.1.3 on 2020-11-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_customermodal'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=10)),
                ('ordereditem', models.CharField(max_length=10)),
            ],
        ),
    ]
