# Generated by Django 3.1.3 on 2020-11-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0003_orderdmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdmodel',
            name='status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
